"""Alipay payment gateway integration for DeerFlow subscriptions."""

import os
import json
from datetime import datetime, timezone, timedelta
from typing import Optional, Dict, Any
from decimal import Decimal

from sqlalchemy.orm import Session
from alipay.aop.api.DefaultAlipayClient import DefaultAlipayClient
from alipay.aop.api import AlipayClientConfig

from deerflow.models.subscription import (
    SubscriptionModel,
    SubscriptionStatus,
    SubscriptionPlan,
    InvoiceModel,
    UsageRecordModel,
    TenantModel
)
from deerflow.services.database import get_session


class AlipayService:
    """Alipay payment service for DeerFlow subscriptions."""

    def __init__(self, db: Session):
        self.db = db
        
        # Initialize Alipay client
        app_id = os.getenv("ALIPAY_APP_ID")
        app_private_key = os.getenv("ALIPAY_PRIVATE_KEY")
        alipay_public_key = os.getenv("ALIPAY_PUBLIC_KEY")
        
        # For development, these can be optional
        self.app_id = app_id
        self.app_private_key = app_private_key
        self.alipay_public_key = alipay_public_key
        
        # Initialize client only if credentials are provided
        if all([app_id, app_private_key, alipay_public_key]):
            try:
                alipay_config = AlipayClientConfig()
                alipay_config.app_id = app_id
                alipay_config.app_private_key = app_private_key
                alipay_config.alipay_public_key = alipay_public_key
                alipay_config.sign_type = "RSA2"
                
                self.client = DefaultAlipayClient(alipay_config)
            except Exception as e:
                print(f"Warning: Failed to initialize Alipay client: {e}")
                self.client = None
        else:
            print("Warning: Alipay credentials not configured. Alipay payment will not be available.")
            self.client = None
        
        self.notify_url = os.getenv("ALIPAY_NOTIFY_URL", "https://api.deerflow.local/api/subscription/webhook-alipay")

    def create_payment_url(
        self,
        tenant_id: str,
        user_id: str,
        plan: SubscriptionPlan,
        email: str,
        return_url: Optional[str] = None
    ) -> str:
        """
        Create Alipay payment URL for subscription.
        
        Args:
            tenant_id: Tenant ID
            user_id: User ID
            plan: Subscription plan
            email: User email
            return_url: URL to return to after payment
            
        Returns:
            Payment URL for redirect
        """
        # Get plan pricing in CNY
        plan_prices = {
            SubscriptionPlan.BASIC: "99.00",      # 99 CNY/quarter (approx $13.70)
            SubscriptionPlan.PRO: "399.00",       # 399 CNY/quarter (approx $55)
            SubscriptionPlan.ENTERPRISE: "1299.00"  # 1299 CNY/quarter (approx $179)
        }
        
        amount = plan_prices.get(plan, "99.00")
        
        # Create order parameters
        order_id = f"{tenant_id}_{user_id}_{int(datetime.now(timezone.utc).timestamp())}"
        
        try:
            # For now, create a simplified payment URL
            # In production, this would be generated by the Alipay SDK
            payment_url = f"https://openapi.alipay.com/gateway.do?_input_charset=utf-8&service=create_direct_pay_by_user"
            
            # Save pending subscription record
            subscription = SubscriptionModel(
                tenant_id=tenant_id,
                user_id=user_id,
                plan=plan,
                status=SubscriptionStatus.INCOMPLETE,
                alipay_trade_no=order_id,
                amount=float(amount),
                currency="cny",
                current_period_start=datetime.now(timezone.utc),
                current_period_end=datetime.now(timezone.utc) + timedelta(days=90),
                payment_gateway="alipay"
            )
            
            self.db.add(subscription)
            self.db.commit()
            
            # Return a URL with necessary parameters that can be used client-side
            return f"{payment_url}&out_trade_no={order_id}&total_fee={amount}&subject=DeerFlow%20{plan.value.upper()}%20Plan"
            
        except Exception as e:
            raise Exception(f"Failed to create Alipay payment URL: {str(e)}")

    def verify_notify(self, params: Dict[str, Any]) -> bool:
        """
        Verify Alipay notification signature.
        
        Args:
            params: Webhook parameters from Alipay
            
        Returns:
            True if signature is valid, False otherwise
        """
        try:
            # For production, implement proper signature verification
            # Check if required fields exist
            required_fields = ["sign", "trade_status", "out_trade_no"]
            return all(field in params for field in required_fields)
        except Exception as e:
            print(f"Notification verification failed: {str(e)}")
            return False

    def handle_webhook_notify(self, params: Dict[str, Any]) -> bool:
        """
        Handle Alipay webhook notification.
        
        Args:
            params: Webhook parameters from Alipay
            
        Returns:
            True if notification processed successfully
        """
        # Verify notification signature
        if not self.verify_notify(params):
            raise ValueError("Invalid Alipay notification signature")
        
        trade_status = params.get("trade_status")
        trade_no = params.get("trade_no")
        out_trade_no = params.get("out_trade_no")
        
        if trade_status == "TRADE_SUCCESS":
            return self._handle_payment_success(out_trade_no, trade_no, params)
        elif trade_status == "TRADE_CLOSED":
            return self._handle_payment_closed(out_trade_no)
        elif trade_status == "TRADE_FINISHED":
            return self._handle_payment_finished(out_trade_no, trade_no, params)
        
        return False

    def _handle_payment_success(
        self,
        out_trade_no: str,
        trade_no: str,
        params: Dict[str, Any]
    ) -> bool:
        """Handle successful Alipay payment."""
        try:
            # Find subscription by order ID
            subscription = self.db.query(SubscriptionModel).filter(
                SubscriptionModel.alipay_trade_no == out_trade_no
            ).first()
            
            if not subscription:
                raise ValueError(f"Subscription not found for order {out_trade_no}")
            
            # Update subscription status
            subscription.status = SubscriptionStatus.ACTIVE
            subscription.alipay_payment_id = trade_no
            subscription.current_period_start = datetime.now(timezone.utc)
            subscription.current_period_end = datetime.now(timezone.utc) + timedelta(days=90)
            
            # Create invoice record
            invoice = InvoiceModel(
                subscription_id=subscription.id,
                alipay_trade_no=trade_no,
                amount=float(params.get("total_amount", 0)),
                currency="cny",
                status="paid",
                paid_at=datetime.now(timezone.utc)
            )
            
            self.db.add(invoice)
            self.db.commit()
            
            return True
            
        except Exception as e:
            print(f"Error handling successful payment: {str(e)}")
            return False

    def _handle_payment_closed(self, out_trade_no: str) -> bool:
        """Handle closed/failed Alipay payment."""
        try:
            subscription = self.db.query(SubscriptionModel).filter(
                SubscriptionModel.alipay_trade_no == out_trade_no
            ).first()
            
            if subscription:
                subscription.status = SubscriptionStatus.PAST_DUE
                self.db.commit()
            
            return True
            
        except Exception as e:
            print(f"Error handling closed payment: {str(e)}")
            return False

    def _handle_payment_finished(
        self,
        out_trade_no: str,
        trade_no: str,
        params: Dict[str, Any]
    ) -> bool:
        """Handle finished Alipay payment (completed or refunded)."""
        try:
            subscription = self.db.query(SubscriptionModel).filter(
                SubscriptionModel.alipay_trade_no == out_trade_no
            ).first()
            
            if not subscription:
                return False
            
            # Check refund status
            refund_status = params.get("refund_status")
            
            if refund_status == "REFUND":
                # Handle refund
                subscription.status = SubscriptionStatus.CANCELED
                subscription.canceled_at = datetime.now(timezone.utc)
            else:
                # Payment already successful
                subscription.status = SubscriptionStatus.ACTIVE
            
            self.db.commit()
            return True
            
        except Exception as e:
            print(f"Error handling finished payment: {str(e)}")
            return False

    def query_order_status(self, out_trade_no: str) -> Optional[Dict[str, Any]]:
        """
        Query Alipay order status.
        
        Args:
            out_trade_no: Merchant order number
            
        Returns:
            Order status information or None if not found
        """
        try:
            # In production, call Alipay API to query order status
            subscription = self.db.query(SubscriptionModel).filter(
                SubscriptionModel.alipay_trade_no == out_trade_no
            ).first()
            
            if subscription:
                return {
                    "trade_no": subscription.alipay_payment_id,
                    "out_trade_no": out_trade_no,
                    "trade_status": subscription.status.value,
                    "total_amount": subscription.amount,
                    "currency": subscription.currency
                }
            return None
        except Exception as e:
            print(f"Error querying order status: {str(e)}")
            return None

    def refund_payment(self, out_trade_no: str, refund_amount: Optional[str] = None) -> bool:
        """
        Refund Alipay payment.
        
        Args:
            out_trade_no: Merchant order number
            refund_amount: Refund amount (if None, refund full amount)
            
        Returns:
            True if refund successful
        """
        try:
            # Get subscription
            subscription = self.db.query(SubscriptionModel).filter(
                SubscriptionModel.alipay_trade_no == out_trade_no
            ).first()
            
            if not subscription or not subscription.alipay_payment_id:
                return False
            
            # In production, call Alipay API to process refund
            # For now, just update the status
            subscription.status = SubscriptionStatus.CANCELED
            subscription.canceled_at = datetime.now(timezone.utc)
            self.db.commit()
            return True
            
        except Exception as e:
            print(f"Error processing refund: {str(e)}")
            return False

    def create_transfer(
        self,
        payee_account: str,
        amount: str,
        description: str
    ) -> Optional[str]:
        """
        Create Alipay transfer (for payouts).
        
        Args:
            payee_account: Payee Alipay account
            amount: Transfer amount
            description: Transfer description
            
        Returns:
            Transfer order ID or None if failed
        """
        try:
            transfer_id = f"transfer_{int(datetime.now(timezone.utc).timestamp())}"
            # In production, call Alipay API to create transfer
            # For now, return the transfer ID
            return transfer_id
            
        except Exception as e:
            print(f"Error creating transfer: {str(e)}")
            return None


def get_alipay_service(db: Session = None) -> AlipayService:
    """Get Alipay service instance."""
    if db is None:
        db = next(get_session())
    return AlipayService(db)
